### ISSUE TITLE
examples won't run, import error

### ISSUE THREAD

**Issue by koaning** [koaning/evol#10]
I am having trouble making sense of this one. 

```
➜  evol git:(master) ✗ pip uninstall evol; pip install .
Uninstalling evol-0.1:
  /anaconda/lib/python3.6/site-packages/evol-0.1-py3.6.egg-info
Proceed (y/n)? y
  Successfully uninstalled evol-0.1
Processing /Users/code/Development/evol
Requirement already satisfied: pytest in /anaconda/lib/python3.6/site-packages (from evol==0.1)
Requirement already satisfied: py>=1.4.29 in /anaconda/lib/python3.6/site-packages (from pytest->evol==0.1)
Requirement already satisfied: setuptools in /anaconda/lib/python3.6/site-packages (from pytest->evol==0.1)
Installing collected packages: evol
  Running setup.py install for evol ... done
Successfully installed evol-0.1
➜  evol git:(master) ✗ python examples/example_pheromone.py
Traceback (most recent call last):
  File "examples/example_pheromone.py", line 13, in <module>
    from evol import Population, Evolution
  File "/anaconda/lib/python3.6/site-packages/evol/__init__.py", line 2, in <module>
    from .evolution import Evolution
  File "/anaconda/lib/python3.6/site-packages/evol/evolution.py", line 3, in <module>
    from .population import Population
  File "/anaconda/lib/python3.6/site-packages/evol/population.py", line 2, in <module>
    from evol.helpers.utils import select_arguments
  File "/anaconda/lib/python3.6/site-packages/evol/helpers.py", line 6, in <module>
    from evol.population import Population
ImportError: cannot import name 'Population'
```

Did you get something similar? I am wondering if this is my system that is acting up.

**Comment by koaning** [comment]
This is very strange. It keep installing a version of `helpers` that I do not have locally. Somehow it produces this on my side. 

```
import random
import numpy as np
from functools import reduce
from typing import Callable
from itertools import accumulate
from evol.population import Population
from evol.individual import Individual

def select_randomly(n_parents=2) -> Callable:
    """
    
    :param n_parents: 
    :return: 
    """
    def f(population: Population):
        return random.choices(population, k=n_parents)
    return f

def select_probibalistic(n_parents=2, key=lambda x:x) -> Callable:
    """
    This function will select parents from a population. It will do this based
    on the value scaled probability. You can scale the probability manually by
    supplying a key function.
    :param n_parents: Number of parents to select per offspring.
    :param key: Functional that maps Individual.value before mapping it to a probability
    :return: 
    """
    def f(population):
        cum_sum_weights = accumulate([key(i.value)for i in population])
        return random.choices(population, cum_weights=cum_sum_weights, k=n_parents)
    return f

def select_min_value(n_parents=2, min_v=None):
    """
    
    :param n_parents: 
    :param min_v: 
    :return: 
    """
    def f(population: Population) -> Callable:
        if min_v == None:
            min_v = np.median([i.value for i in population])
        return random.choices([i for i in population if i.value >= min_v], k=n_parents)
    return f

def gaussian_mutation(mu=0, sigma=1):
    """
    
    :param mu: 
    :param sigma: 
    :return: 
    """
    def f(i:Individual):
        i.change_chromosome([g + random.normalvariate(mu, sigma) for g in i.chromosome])
    return f
```

**Comment by koaning** [comment]
This is very odd. It even does it after I delete the git repo and start anew with a virtualenv.

**Comment by rogiervandergeer** [comment]
Tbh I just add the path of `evol` to the virtualenv (`add2virtualenv`), so I don't actually install the package.

**Comment by rogiervandergeer** [comment]
So it seems it doesn't install helpers at all

**Comment by koaning** [comment]
That makes some sense actually. It probably never replaced an old file. This python package installing stuff is messy ...

**Comment by rogiervandergeer** [comment]
Fixed it. Wasn't too difficult actually.
